spring:
  application:
    name: notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_EMAIL}
    password: ${SENDER_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: ${HOST_PORT}