spring:
  application:
    name: notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: someuser@email.com
    password: some password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8082
logging:
  level:
    root: DEBUG